// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type File struct {
	ID string `json:"id"`
}

type Mutation struct {
}

type Query struct {
}

type ToDo struct {
	ID          string `json:"id"`
	Description string `json:"description"`
	FileID      string `json:"file_id"`
	DueDate     string `json:"due_date"`
}
