package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	domain "awesomeProject1/internal/domain/todo"
	"context"
	"strconv"
	"time"

	"github.com/99designs/gqlgen/graphql"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, description string, fileID string, dueDate string) (*ToDo, error) {
	layout := "2006-01-02"
	t, err := time.Parse(layout, dueDate)
	if err != nil {
		return nil, err
	}

	todo := &domain.ToDo{
		Description: description,
		FileID:      fileID,
		DueDate:     t,
	}

	todo, err = r.TodoUC.CreateTodo(ctx, todo)
	if err != nil {
		return nil, err
	}

	return &ToDo{
		ID:          strconv.FormatUint(todo.ID, 10),
		Description: todo.Description,
		FileID:      todo.FileID,
		DueDate:     todo.DueDate.String(),
	}, err
}

// UploadFile is the resolver for the uploadFile field.
func (r *mutationResolver) UploadFile(ctx context.Context, file *graphql.Upload) (*File, error) {
	return &File{ID: "1"}, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*ToDo, error) {
	list, err := r.TodoUC.Execute(ctx)
	if err != nil {
		return nil, err
	}

	todos := []*ToDo{}

	for _, item := range list {
		todos = append(todos, &ToDo{
			ID:          strconv.FormatUint(item.ID, 10),
			Description: item.Description,
			FileID:      item.FileID,
			DueDate:     item.DueDate.String(),
		})
	}

	return todos, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
